* 序言
富甲天下3的终极修改版本很有意思，和暗黑破坏神2的刷符文一样充满刺激。避免玩家因为策略失误导致游戏性下降，故写此攻略。

* 理论
** 富甲3全国地图终极修改V5.0攻略
*** 前提
- 允许无限SL
- 禁武器：金箍棒
- 禁攻城器械：加农炮
由于难度实在太大，第一次刘备通关用了24H，还是在无限SL情况，如果没有，实在是太难。

富甲天下，赚钱优先！
*** 前期——招募将领
优先招募将领，且优先有运输的将领，因为运输可以提高贸易效率，有了钱还怕啥？
*** 中期——贸易生财
运输将领凑齐后，全国贸易生财。

- 如果遇到聚贤庄，优先怕死将领（例如姜维等高逃跑的将领），因为不怕死将领容易被打死，可以去医院复活（前期不用急着复活），怕死将领被电脑招募后，就永远招募不了了。（这条用于统招版）
- 如果遇到锦囊铺，至少刷1个暗渡陈仓、以逸待劳、严阵以待（'、'表示或者，1个是因为避免SL无聊）。如果钱足，遇到过河拆迁或杀人放火，也买，用于破坏4大城洛阳、长安、成都、荆州。
- 如果遇到医院，优先强身，不用优先复活。
- 如果遇到武馆，优先武力，因为野战属性太多，分散了属性点。
- 如果遇到书馆，优先智力，因为智力在单挑和野战都有用。
- 如果遇到武器店，单挑将惯石枪或屠龙刀、野战将倚天剑、军师水镜扇。
- 如果遇到机关店，优先杀伤，因为破坏城池意义不大。
*** 后期——攻城拔寨
攻城策略：至少身上有锦囊三宝之一，暗渡陈仓、以逸待劳、严阵以待，用于攻城后建造特产坊（严阵以待可能会用不上）！优先有特产的，还是那句话，有了钱还怕啥？然后继续贸易生财。

- 如果遇到没有特产的城池，不攻，因为无法提高贸易效率，还要分配将领、士兵把守。
*** 终期——统一全国
这个时候，基本占领了主要的城市（有特产的城池），就等着电脑主动来送，不可胜在己，可胜在敌。

- 如果遇到没有特产的城池，攻但是不占，削弱分散电脑资源。
*** 经验
后期敌人曹操很顽强，因为统率高，可以野战，而且典韦血高攻高，可以单挑。

城池里不用留钱，钱用来投资比留在城池里好的多（除非钱很多），富甲天下。

尽量使用9格骰子，方便SL，12格需要SL更多次。

有暗渡陈仓就去成都区域刷数据，那里有3个锦囊铺和1个聚贤庄和1个募兵所和1个机关所。

智力底下的将领使用"以逸待劳"会失败。
*** 攻略FAQ
**** 前期兵力不足如何防守攻城？
SL，别无他法。
** 将领
- 体力：140 130
- 武力：110 100
- 军师智力：110 100
- 将军智力：80 70


- 高体高武低智：例如许褚、文丑。
- 高体中武中智：例如夏侯渊、关兴、程普。
- 高体中武低智：例如曹洪、沙摩柯
- 中体高武高智：例如张辽、关羽。
- 中体高武中智：例如庞德、黄忠、孙策。
- 中体高武低智：例如夏侯惇、张飞。
- 中体中武高智：例如张合、孙坚。 
- 中体中武中智：例如徐晃。
- 中体中武低智：例如曹仁、张苞、周泰。
** 建筑
*** 城池
**** 城池过路费
主要和发展金有关。
| 规模 | 过路费MAX |
|    6 | 5w+       |
|    5 | 2w+       |
|    4 | 1w+       |
|    3 | 5k+       |
**** 城池将领
- 太守：智力将领上，用于提升发展金。
- 校尉：统率将领上，用于野战和提升征兵的速度。
- 守将：怕死将领上，用于单挑消耗恶心电脑。
- 守将2：强力将领上（5-6规模城池用怕死的，4规模城池用不怕死的，3规模城池不用放），用于单挑击败电脑。
**** 城池征兵所
5级征兵所（最高等级）一天增加200+士兵。
**** 城池市集
200商业度一天增加300+金钱。
*** 募兵所
| 士兵数 | 金钱数 |
| 1k     | 1k     |
| 5k     | 1w     |
| 1w     | 5w     |
| 2w     | 15w    |
*** 锦囊铺
介绍重要锦囊。

- 暗渡陈仓、以逸待劳、严阵以待：用于到达指定地点，效果依次递减。
- 回光返照：用于培养单挑达人。
- 临危不惧：用于避免敌人的打草惊蛇、釜底抽薪的锦囊损失。
- 无懈可击：避免敌人的借刀杀人。
- 临阵磨枪：用于攻城，减少士兵损失。
- 笑里藏刀、无所遁形：用于减少SL次数，意义不大。
- 过河拆桥、放火杀人：用于减少5-6规模大城的征兵，避免攻城时城池兵力达到10w（一般不可能，中立城池只有一个征兵所，不用刻意刷）。
* 实例
敌人超过25逃跑，都不读档斩杀。？基本上杀不死

让电脑占城。？阵亡敌将。

用心一也，速度募兵。

** DONE 如何富甲天下3查看数据文件？
   CLOSED: [2017-08-01 Tue 11:13]
？修改武将数据。

#+BEGIN_VERSE
http://blog.sina.com.cn/s/blog_50c49cb50100rojr.html
FPE
#+END_VERSE
* 参考
#+BEGIN_VERSE
https://tieba.baidu.com/p/2750886182

刘备6格，曹操7格，孙权8格，袁绍10格。 https://tieba.baidu.com/p/2750886182?pn=1

电脑五倍兵攻城 https://tieba.baidu.com/p/2750886182?pn=2

骰子赌场出错，Tab+f1+Backspace，输入ru4a.62 https://tieba.baidu.com/p/2750886182?pn=4

https://www.ptt.cc/bbs/Old-Games/M.1325651773.A.C90.html
#+END_VERSE
